FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

ADD ./bin/mcc /usr/local/bin/
ADD ./bin/mccutl /usr/local/bin/
ADD ./bin/mccctl /usr/local/bin/
RUN mkdir -p /var/etcd/
RUN mkdir -p /var/lib/etcd/

EXPOSE 2379 2380

# Define default command.
CMD ["/usr/local/bin/mcc"]
